language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install nodejs -y
  - sudo apt-get install doxygen -y
  - sudo npm install -g mocha
  - sudo npm install -g node-gyp
script: make test && make package && make node-test
