language: node_js

cache:
  npm: true
  ccache: true

node_js:
  - stable
  - 14
  - 12
  - 10

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install --build-from-source

# Post-install test scripts.
script:
  - export PATH="/usr/lib/ccache/:$PATH"
  - if [ $TRAVIS_NODE_VERSION == "stable" ]; then
      make test VERBOSE=1;
      make package VERBOSE=1;
      make benchmark VERBOSE=1;
    fi

  - npm test

after_success:
  - npm run deploy
