name: Publish opencc-wasm to npm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-package-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasm-lib
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Emscripten
        # See https://github.com/emscripten-core/emsdk/tags
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.22

      - name: Verify
        run: em++ -v

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v3

      - name: Install dependencies
        run: npm ci

      - name: Refresh wasm-lib assets
        run: ./scripts/refresh_assets.sh

      - name: Package wasm-lib (includes build)
        run: npm pack

      - name: Publish to npm
        run: npm publish --provenance
        env:
          NPM_CONFIG_PROVENANCE: true
